import React from "react";
const Terms=()=>
{
    return(
        <div>
            &nbsp;
            <div className="mt-4 p-3 background-overlay">
               <h1 className="text-center my-3">TERMS & CONDITIONS</h1>
                <p>The Doge Pound is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to buy digital collectibles in presale. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions andcontracts generated by this website before approval. Furthermore, as The Doge Pound smart contract runs on theEthereum network, there is no ability to undo, reverse, or restoreany transactions.</p>
                <p>This website and its connected services are provided “as is” and“as available” without a warranty of any kind. By using this website, you are accepting sole responsibility for any and all transactions involving The Doge Pound digital collectibles.</p>
                <h1 className="mt-2">OWNERSHIP</h1>
                <ul>
                    <li className="my-3">
                        <h5>You Own the NFT</h5>
                        <ul>
                            <li>Each The Doge Pound is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying The Doge Pound Token, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any The Doge Pound Token.</li>
                        </ul>
                    </li>

                    <li className="my-3">
                        <h5>Personal Use</h5>
                        Subject to your continued compliance with these Terms, we grant you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely for the following purposes:
                        <ul>
                            <li>for your own personal, non-commercial use.</li>
                            <li>as part of a marketplace that permits the purchase and sale of your Doge Token /NFT, provided that the marketplace cryptographically verifies each Doge Pound Token owner’s rights to display the Art for their Doge Pound Token to ensure that only the actual owner can display the Art.</li>
                            <li>as part of a third-party website or application that permits theinclusion, involvement, or participation of your Doge Pound Token, provided that the website/application cryptographically verifieseach Doge Pound Token owner’s rights to display the Art for their Doge Pound Token to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of The Doge Pound Token leaves the website/application.</li>
                        </ul>
                    </li>

                    <li className="my-3">
                        <h5>Commercial Use</h5>
                        Subject to your continued compliance with these Terms, we grantyou an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works basedupon the Art (“Commercial Use”). Examples of such CommercialUse would e.g., be the use of the Art to produce and sell merchandise products (T-Shirts, etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from
                        <ul>
                            <li>owning or operating a marketplace that permits the use and sale of The Doge Pound Token generally, provided that the marketplace cryptographically verifies each Doge Pound Token owner’s rights to display the Art for their Doge Pound Token to ensure that only the actual owner can display the Art.</li>
                            <li>owning or operating a third-party website or application that permits the inclusion, involvement, or participation of Doge Pound Tokens generally, provided that the third-party website or application cryptographically verifies each The Doge Pound Token owner’srights to display the Art for their Doge Pound Token to ensure that onlythe actual owner can display the Art, and provided that the Art is no longer visible once the owner of the purchased Doge Pound Token leaves the website/application;</li>
                            <li>or earning revenue from any of the foregoing.</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    )
}
export default Terms;
